package com.sdxm.service3rd.entity;

public class ThirdpartyService {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thirdparty_service.id
     *
     * @mbg.generated Fri Aug 31 16:00:52 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thirdparty_service.type
     *
     * @mbg.generated Fri Aug 31 16:00:52 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thirdparty_service.logo_image
     *
     * @mbg.generated Fri Aug 31 16:00:52 CST 2018
     */
    private String logoImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thirdparty_service.name
     *
     * @mbg.generated Fri Aug 31 16:00:52 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thirdparty_service.url
     *
     * @mbg.generated Fri Aug 31 16:00:52 CST 2018
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thirdparty_service.id
     *
     * @return the value of thirdparty_service.id
     *
     * @mbg.generated Fri Aug 31 16:00:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thirdparty_service.id
     *
     * @param id the value for thirdparty_service.id
     *
     * @mbg.generated Fri Aug 31 16:00:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thirdparty_service.type
     *
     * @return the value of thirdparty_service.type
     *
     * @mbg.generated Fri Aug 31 16:00:52 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thirdparty_service.type
     *
     * @param type the value for thirdparty_service.type
     *
     * @mbg.generated Fri Aug 31 16:00:52 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thirdparty_service.logo_image
     *
     * @return the value of thirdparty_service.logo_image
     *
     * @mbg.generated Fri Aug 31 16:00:52 CST 2018
     */
    public String getLogoImage() {
        return logoImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thirdparty_service.logo_image
     *
     * @param logoImage the value for thirdparty_service.logo_image
     *
     * @mbg.generated Fri Aug 31 16:00:52 CST 2018
     */
    public void setLogoImage(String logoImage) {
        this.logoImage = logoImage == null ? null : logoImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thirdparty_service.name
     *
     * @return the value of thirdparty_service.name
     *
     * @mbg.generated Fri Aug 31 16:00:52 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thirdparty_service.name
     *
     * @param name the value for thirdparty_service.name
     *
     * @mbg.generated Fri Aug 31 16:00:52 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thirdparty_service.url
     *
     * @return the value of thirdparty_service.url
     *
     * @mbg.generated Fri Aug 31 16:00:52 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thirdparty_service.url
     *
     * @param url the value for thirdparty_service.url
     *
     * @mbg.generated Fri Aug 31 16:00:52 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}