package com.sdxm.report.dao;

import com.sdxm.report.entity.ReportAttachment;
import com.sdxm.report.entity.ReportAttachmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReportAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_attachment
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    long countByExample(ReportAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_attachment
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    int deleteByExample(ReportAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_attachment
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_attachment
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    int insert(ReportAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_attachment
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    int insertSelective(ReportAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_attachment
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    List<ReportAttachment> selectByExample(ReportAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_attachment
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    ReportAttachment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_attachment
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    int updateByExampleSelective(@Param("record") ReportAttachment record, @Param("example") ReportAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_attachment
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    int updateByExample(@Param("record") ReportAttachment record, @Param("example") ReportAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_attachment
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    int updateByPrimaryKeySelective(ReportAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_attachment
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    int updateByPrimaryKey(ReportAttachment record);
}