package com.sdxm.report.dao;

import com.sdxm.report.entity.Report;
import com.sdxm.report.entity.ReportExample;

import java.util.HashMap;
import java.util.List;

import com.sdxm.report.vo.ReportExt;
import org.apache.ibatis.annotations.Param;

public interface ReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated Sat Sep 01 10:52:28 CST 2018
     */
    long countByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated Sat Sep 01 10:52:28 CST 2018
     */
    int deleteByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated Sat Sep 01 10:52:28 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated Sat Sep 01 10:52:28 CST 2018
     */
    int insert(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated Sat Sep 01 10:52:28 CST 2018
     */
    int insertSelective(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated Sat Sep 01 10:52:28 CST 2018
     */
    List<Report> selectByExampleWithBLOBs(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated Sat Sep 01 10:52:28 CST 2018
     */
    List<Report> selectByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated Sat Sep 01 10:52:28 CST 2018
     */
    Report selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated Sat Sep 01 10:52:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") Report record, @Param("example") ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated Sat Sep 01 10:52:28 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Report record, @Param("example") ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated Sat Sep 01 10:52:28 CST 2018
     */
    int updateByExample(@Param("record") Report record, @Param("example") ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated Sat Sep 01 10:52:28 CST 2018
     */
    int updateByPrimaryKeySelective(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated Sat Sep 01 10:52:28 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated Sat Sep 01 10:52:28 CST 2018
     */
    int updateByPrimaryKey(Report record);

    /**
     * 查询上报列表
     *
     * @param map
     */
    List<ReportExt> select(HashMap<String, Object> map);

    /**
     * 查询通知
     *
     * @param
     */
    List<ReportExt> queryMessage();
}