package com.sdxm.report.dao;


import com.sdxm.report.entity.SysEmployee;
import com.sdxm.report.entity.SysEmployeeExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface SysEmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    long countByExample(SysEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    int deleteByExample(SysEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    int insert(SysEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    int insertSelective(SysEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    List<SysEmployee> selectByExample(SysEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    SysEmployee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysEmployee record, @Param("example") SysEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    int updateByExample(@Param("record") SysEmployee record, @Param("example") SysEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    int updateByPrimaryKeySelective(SysEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    int updateByPrimaryKey(SysEmployee record);

    @Select("SET NAMES 'utf8mb4'")
    public void setUTF8MB4();
}