package com.sdxm.dictionary.entity;

public class Valuelist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column valuelist.id
     *
     * @mbg.generated Thu Aug 30 21:26:13 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column valuelist.code
     *
     * @mbg.generated Thu Aug 30 21:26:13 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column valuelist.name
     *
     * @mbg.generated Thu Aug 30 21:26:13 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column valuelist.remark
     *
     * @mbg.generated Thu Aug 30 21:26:13 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column valuelist.parent_code
     *
     * @mbg.generated Thu Aug 30 21:26:13 CST 2018
     */
    private String parentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column valuelist.sequence
     *
     * @mbg.generated Thu Aug 30 21:26:13 CST 2018
     */
    private Integer sequence;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column valuelist.id
     *
     * @return the value of valuelist.id
     *
     * @mbg.generated Thu Aug 30 21:26:13 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column valuelist.id
     *
     * @param id the value for valuelist.id
     *
     * @mbg.generated Thu Aug 30 21:26:13 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column valuelist.code
     *
     * @return the value of valuelist.code
     *
     * @mbg.generated Thu Aug 30 21:26:13 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column valuelist.code
     *
     * @param code the value for valuelist.code
     *
     * @mbg.generated Thu Aug 30 21:26:13 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column valuelist.name
     *
     * @return the value of valuelist.name
     *
     * @mbg.generated Thu Aug 30 21:26:13 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column valuelist.name
     *
     * @param name the value for valuelist.name
     *
     * @mbg.generated Thu Aug 30 21:26:13 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column valuelist.remark
     *
     * @return the value of valuelist.remark
     *
     * @mbg.generated Thu Aug 30 21:26:13 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column valuelist.remark
     *
     * @param remark the value for valuelist.remark
     *
     * @mbg.generated Thu Aug 30 21:26:13 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column valuelist.parent_code
     *
     * @return the value of valuelist.parent_code
     *
     * @mbg.generated Thu Aug 30 21:26:13 CST 2018
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column valuelist.parent_code
     *
     * @param parentCode the value for valuelist.parent_code
     *
     * @mbg.generated Thu Aug 30 21:26:13 CST 2018
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column valuelist.sequence
     *
     * @return the value of valuelist.sequence
     *
     * @mbg.generated Thu Aug 30 21:26:13 CST 2018
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column valuelist.sequence
     *
     * @param sequence the value for valuelist.sequence
     *
     * @mbg.generated Thu Aug 30 21:26:13 CST 2018
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }
}