package com.anrong.urpm.entity;

public class SysLogWithBLOBs extends SysLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.data1
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    private String data1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.data2
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    private String data2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.data3
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    private String data3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.data4
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    private String data4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.data5
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    private String data5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.data6
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    private String data6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.data7
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    private String data7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.data8
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    private String data8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.data9
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    private String data9;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.data1
     *
     * @return the value of sys_log.data1
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    public String getData1() {
        return data1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.data1
     *
     * @param data1 the value for sys_log.data1
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    public void setData1(String data1) {
        this.data1 = data1 == null ? null : data1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.data2
     *
     * @return the value of sys_log.data2
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    public String getData2() {
        return data2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.data2
     *
     * @param data2 the value for sys_log.data2
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    public void setData2(String data2) {
        this.data2 = data2 == null ? null : data2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.data3
     *
     * @return the value of sys_log.data3
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    public String getData3() {
        return data3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.data3
     *
     * @param data3 the value for sys_log.data3
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    public void setData3(String data3) {
        this.data3 = data3 == null ? null : data3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.data4
     *
     * @return the value of sys_log.data4
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    public String getData4() {
        return data4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.data4
     *
     * @param data4 the value for sys_log.data4
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    public void setData4(String data4) {
        this.data4 = data4 == null ? null : data4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.data5
     *
     * @return the value of sys_log.data5
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    public String getData5() {
        return data5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.data5
     *
     * @param data5 the value for sys_log.data5
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    public void setData5(String data5) {
        this.data5 = data5 == null ? null : data5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.data6
     *
     * @return the value of sys_log.data6
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    public String getData6() {
        return data6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.data6
     *
     * @param data6 the value for sys_log.data6
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    public void setData6(String data6) {
        this.data6 = data6 == null ? null : data6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.data7
     *
     * @return the value of sys_log.data7
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    public String getData7() {
        return data7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.data7
     *
     * @param data7 the value for sys_log.data7
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    public void setData7(String data7) {
        this.data7 = data7 == null ? null : data7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.data8
     *
     * @return the value of sys_log.data8
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    public String getData8() {
        return data8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.data8
     *
     * @param data8 the value for sys_log.data8
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    public void setData8(String data8) {
        this.data8 = data8 == null ? null : data8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.data9
     *
     * @return the value of sys_log.data9
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    public String getData9() {
        return data9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.data9
     *
     * @param data9 the value for sys_log.data9
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    public void setData9(String data9) {
        this.data9 = data9 == null ? null : data9.trim();
    }
}