package com.anrong.urpm.entity;

import java.util.Date;

public class SysLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.id
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.who
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    private Integer who;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.create_time
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.id
     *
     * @return the value of sys_log.id
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.id
     *
     * @param id the value for sys_log.id
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.who
     *
     * @return the value of sys_log.who
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    public Integer getWho() {
        return who;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.who
     *
     * @param who the value for sys_log.who
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    public void setWho(Integer who) {
        this.who = who;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.create_time
     *
     * @return the value of sys_log.create_time
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.create_time
     *
     * @param createTime the value for sys_log.create_time
     *
     * @mbg.generated Tue Aug 28 16:01:37 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}