package com.anrong.urpm.entity;

public class SysRolePower {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_power.id
     *
     * @mbg.generated Tue Aug 28 16:01:16 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_power.role_id
     *
     * @mbg.generated Tue Aug 28 16:01:16 CST 2018
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_power.power_id
     *
     * @mbg.generated Tue Aug 28 16:01:16 CST 2018
     */
    private Integer powerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_power.id
     *
     * @return the value of sys_role_power.id
     *
     * @mbg.generated Tue Aug 28 16:01:16 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_power.id
     *
     * @param id the value for sys_role_power.id
     *
     * @mbg.generated Tue Aug 28 16:01:16 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_power.role_id
     *
     * @return the value of sys_role_power.role_id
     *
     * @mbg.generated Tue Aug 28 16:01:16 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_power.role_id
     *
     * @param roleId the value for sys_role_power.role_id
     *
     * @mbg.generated Tue Aug 28 16:01:16 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_power.power_id
     *
     * @return the value of sys_role_power.power_id
     *
     * @mbg.generated Tue Aug 28 16:01:16 CST 2018
     */
    public Integer getPowerId() {
        return powerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_power.power_id
     *
     * @param powerId the value for sys_role_power.power_id
     *
     * @mbg.generated Tue Aug 28 16:01:16 CST 2018
     */
    public void setPowerId(Integer powerId) {
        this.powerId = powerId;
    }
}