package com.sdxm.report.entity;

import java.util.Date;

public class ReportComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_comment.id
     *
     * @mbg.generated Sat Sep 01 10:50:06 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_comment.employee_id
     *
     * @mbg.generated Sat Sep 01 10:50:06 CST 2018
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_comment.create_time
     *
     * @mbg.generated Sat Sep 01 10:50:06 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_comment.report_id
     *
     * @mbg.generated Sat Sep 01 10:50:06 CST 2018
     */
    private Integer reportId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_comment.happiness_code
     *
     * @mbg.generated Sat Sep 01 10:50:06 CST 2018
     */
    private String happinessCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_comment.parent_id
     *
     * @mbg.generated Sat Sep 01 10:50:06 CST 2018
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_comment.happiness_lv
     *
     * @mbg.generated Sat Sep 01 10:50:06 CST 2018
     */
    private Integer happinessLv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_comment.content
     *
     * @mbg.generated Sat Sep 01 10:50:06 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_comment.id
     *
     * @return the value of report_comment.id
     *
     * @mbg.generated Sat Sep 01 10:50:06 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_comment.id
     *
     * @param id the value for report_comment.id
     *
     * @mbg.generated Sat Sep 01 10:50:06 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_comment.employee_id
     *
     * @return the value of report_comment.employee_id
     *
     * @mbg.generated Sat Sep 01 10:50:06 CST 2018
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_comment.employee_id
     *
     * @param employeeId the value for report_comment.employee_id
     *
     * @mbg.generated Sat Sep 01 10:50:06 CST 2018
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_comment.create_time
     *
     * @return the value of report_comment.create_time
     *
     * @mbg.generated Sat Sep 01 10:50:06 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_comment.create_time
     *
     * @param createTime the value for report_comment.create_time
     *
     * @mbg.generated Sat Sep 01 10:50:06 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_comment.report_id
     *
     * @return the value of report_comment.report_id
     *
     * @mbg.generated Sat Sep 01 10:50:06 CST 2018
     */
    public Integer getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_comment.report_id
     *
     * @param reportId the value for report_comment.report_id
     *
     * @mbg.generated Sat Sep 01 10:50:06 CST 2018
     */
    public void setReportId(Integer reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_comment.happiness_code
     *
     * @return the value of report_comment.happiness_code
     *
     * @mbg.generated Sat Sep 01 10:50:06 CST 2018
     */
    public String getHappinessCode() {
        return happinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_comment.happiness_code
     *
     * @param happinessCode the value for report_comment.happiness_code
     *
     * @mbg.generated Sat Sep 01 10:50:06 CST 2018
     */
    public void setHappinessCode(String happinessCode) {
        this.happinessCode = happinessCode == null ? null : happinessCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_comment.parent_id
     *
     * @return the value of report_comment.parent_id
     *
     * @mbg.generated Sat Sep 01 10:50:06 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_comment.parent_id
     *
     * @param parentId the value for report_comment.parent_id
     *
     * @mbg.generated Sat Sep 01 10:50:06 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_comment.happiness_lv
     *
     * @return the value of report_comment.happiness_lv
     *
     * @mbg.generated Sat Sep 01 10:50:06 CST 2018
     */
    public Integer getHappinessLv() {
        return happinessLv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_comment.happiness_lv
     *
     * @param happinessLv the value for report_comment.happiness_lv
     *
     * @mbg.generated Sat Sep 01 10:50:06 CST 2018
     */
    public void setHappinessLv(Integer happinessLv) {
        this.happinessLv = happinessLv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_comment.content
     *
     * @return the value of report_comment.content
     *
     * @mbg.generated Sat Sep 01 10:50:06 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_comment.content
     *
     * @param content the value for report_comment.content
     *
     * @mbg.generated Sat Sep 01 10:50:06 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}