package com.sdxm.report.entity;

import java.util.Date;

public class ReportAttachment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_attachment.id
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_attachment.report_id
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    private Integer reportId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_attachment.name
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_attachment.url
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_attachment.create_time
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_attachment.id
     *
     * @return the value of report_attachment.id
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_attachment.id
     *
     * @param id the value for report_attachment.id
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_attachment.report_id
     *
     * @return the value of report_attachment.report_id
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    public Integer getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_attachment.report_id
     *
     * @param reportId the value for report_attachment.report_id
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    public void setReportId(Integer reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_attachment.name
     *
     * @return the value of report_attachment.name
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_attachment.name
     *
     * @param name the value for report_attachment.name
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_attachment.url
     *
     * @return the value of report_attachment.url
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_attachment.url
     *
     * @param url the value for report_attachment.url
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_attachment.create_time
     *
     * @return the value of report_attachment.create_time
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_attachment.create_time
     *
     * @param createTime the value for report_attachment.create_time
     *
     * @mbg.generated Sat Sep 01 10:51:57 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}