package com.sdxm.report.entity;

import java.util.Date;

public class SysEmployee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.id
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.name
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.mobile
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.email
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.create_time
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.update_time
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.delete_flag
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    private Integer deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.enterprise_id
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    private Integer enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.department_id
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    private Integer departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.user_id
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.role_id
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.open_id
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.nick_name
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.head_url
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    private String headUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.sex
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    private String sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.id
     *
     * @return the value of sys_employee.id
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.id
     *
     * @param id the value for sys_employee.id
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.name
     *
     * @return the value of sys_employee.name
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.name
     *
     * @param name the value for sys_employee.name
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.mobile
     *
     * @return the value of sys_employee.mobile
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.mobile
     *
     * @param mobile the value for sys_employee.mobile
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.email
     *
     * @return the value of sys_employee.email
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.email
     *
     * @param email the value for sys_employee.email
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.create_time
     *
     * @return the value of sys_employee.create_time
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.create_time
     *
     * @param createTime the value for sys_employee.create_time
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.update_time
     *
     * @return the value of sys_employee.update_time
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.update_time
     *
     * @param updateTime the value for sys_employee.update_time
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.delete_flag
     *
     * @return the value of sys_employee.delete_flag
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.delete_flag
     *
     * @param deleteFlag the value for sys_employee.delete_flag
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.enterprise_id
     *
     * @return the value of sys_employee.enterprise_id
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.enterprise_id
     *
     * @param enterpriseId the value for sys_employee.enterprise_id
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.department_id
     *
     * @return the value of sys_employee.department_id
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.department_id
     *
     * @param departmentId the value for sys_employee.department_id
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.user_id
     *
     * @return the value of sys_employee.user_id
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.user_id
     *
     * @param userId the value for sys_employee.user_id
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.role_id
     *
     * @return the value of sys_employee.role_id
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.role_id
     *
     * @param roleId the value for sys_employee.role_id
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.open_id
     *
     * @return the value of sys_employee.open_id
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.open_id
     *
     * @param openId the value for sys_employee.open_id
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.nick_name
     *
     * @return the value of sys_employee.nick_name
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.nick_name
     *
     * @param nickName the value for sys_employee.nick_name
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.head_url
     *
     * @return the value of sys_employee.head_url
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public String getHeadUrl() {
        return headUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.head_url
     *
     * @param headUrl the value for sys_employee.head_url
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public void setHeadUrl(String headUrl) {
        this.headUrl = headUrl == null ? null : headUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.sex
     *
     * @return the value of sys_employee.sex
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.sex
     *
     * @param sex the value for sys_employee.sex
     *
     * @mbg.generated Tue Aug 28 16:03:22 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }
}