package com.sdxm.service3rd.dao;

import com.sdxm.service3rd.entity.ThirdpartyService;
import com.sdxm.service3rd.entity.ThirdpartyServiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ThirdpartyServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdparty_service
     *
     * @mbg.generated Fri Aug 31 14:48:19 CST 2018
     */
    long countByExample(ThirdpartyServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdparty_service
     *
     * @mbg.generated Fri Aug 31 14:48:19 CST 2018
     */
    int deleteByExample(ThirdpartyServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdparty_service
     *
     * @mbg.generated Fri Aug 31 14:48:19 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdparty_service
     *
     * @mbg.generated Fri Aug 31 14:48:19 CST 2018
     */
    int insert(ThirdpartyService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdparty_service
     *
     * @mbg.generated Fri Aug 31 14:48:19 CST 2018
     */
    int insertSelective(ThirdpartyService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdparty_service
     *
     * @mbg.generated Fri Aug 31 14:48:19 CST 2018
     */
    List<ThirdpartyService> selectByExample(ThirdpartyServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdparty_service
     *
     * @mbg.generated Fri Aug 31 14:48:19 CST 2018
     */
    ThirdpartyService selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdparty_service
     *
     * @mbg.generated Fri Aug 31 14:48:19 CST 2018
     */
    int updateByExampleSelective(@Param("record") ThirdpartyService record, @Param("example") ThirdpartyServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdparty_service
     *
     * @mbg.generated Fri Aug 31 14:48:19 CST 2018
     */
    int updateByExample(@Param("record") ThirdpartyService record, @Param("example") ThirdpartyServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdparty_service
     *
     * @mbg.generated Fri Aug 31 14:48:19 CST 2018
     */
    int updateByPrimaryKeySelective(ThirdpartyService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdparty_service
     *
     * @mbg.generated Fri Aug 31 14:48:19 CST 2018
     */
    int updateByPrimaryKey(ThirdpartyService record);
}