package com.anrong.urpm.dao;

import com.anrong.urpm.entity.SysDepartment;
import com.anrong.urpm.entity.SysDepartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbg.generated Tue Aug 28 16:02:58 CST 2018
     */
    long countByExample(SysDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbg.generated Tue Aug 28 16:02:58 CST 2018
     */
    int deleteByExample(SysDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbg.generated Tue Aug 28 16:02:58 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbg.generated Tue Aug 28 16:02:58 CST 2018
     */
    int insert(SysDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbg.generated Tue Aug 28 16:02:58 CST 2018
     */
    int insertSelective(SysDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbg.generated Tue Aug 28 16:02:58 CST 2018
     */
    List<SysDepartment> selectByExample(SysDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbg.generated Tue Aug 28 16:02:58 CST 2018
     */
    SysDepartment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbg.generated Tue Aug 28 16:02:58 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysDepartment record, @Param("example") SysDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbg.generated Tue Aug 28 16:02:58 CST 2018
     */
    int updateByExample(@Param("record") SysDepartment record, @Param("example") SysDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbg.generated Tue Aug 28 16:02:58 CST 2018
     */
    int updateByPrimaryKeySelective(SysDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbg.generated Tue Aug 28 16:02:58 CST 2018
     */
    int updateByPrimaryKey(SysDepartment record);
}