package com.anrong.urpm.dao;

import com.anrong.urpm.entity.SysEnterprise;
import com.anrong.urpm.entity.SysEnterpriseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysEnterpriseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_enterprise
     *
     * @mbg.generated Tue Aug 28 16:02:40 CST 2018
     */
    long countByExample(SysEnterpriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_enterprise
     *
     * @mbg.generated Tue Aug 28 16:02:40 CST 2018
     */
    int deleteByExample(SysEnterpriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_enterprise
     *
     * @mbg.generated Tue Aug 28 16:02:40 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_enterprise
     *
     * @mbg.generated Tue Aug 28 16:02:40 CST 2018
     */
    int insert(SysEnterprise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_enterprise
     *
     * @mbg.generated Tue Aug 28 16:02:40 CST 2018
     */
    int insertSelective(SysEnterprise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_enterprise
     *
     * @mbg.generated Tue Aug 28 16:02:40 CST 2018
     */
    List<SysEnterprise> selectByExample(SysEnterpriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_enterprise
     *
     * @mbg.generated Tue Aug 28 16:02:40 CST 2018
     */
    SysEnterprise selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_enterprise
     *
     * @mbg.generated Tue Aug 28 16:02:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysEnterprise record, @Param("example") SysEnterpriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_enterprise
     *
     * @mbg.generated Tue Aug 28 16:02:40 CST 2018
     */
    int updateByExample(@Param("record") SysEnterprise record, @Param("example") SysEnterpriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_enterprise
     *
     * @mbg.generated Tue Aug 28 16:02:40 CST 2018
     */
    int updateByPrimaryKeySelective(SysEnterprise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_enterprise
     *
     * @mbg.generated Tue Aug 28 16:02:40 CST 2018
     */
    int updateByPrimaryKey(SysEnterprise record);
}