package com.anrong.urpm.dao;

import com.anrong.urpm.entity.SysRolePower;
import com.anrong.urpm.entity.SysRolePowerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRolePowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_power
     *
     * @mbg.generated Tue Aug 28 16:01:16 CST 2018
     */
    long countByExample(SysRolePowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_power
     *
     * @mbg.generated Tue Aug 28 16:01:16 CST 2018
     */
    int deleteByExample(SysRolePowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_power
     *
     * @mbg.generated Tue Aug 28 16:01:16 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_power
     *
     * @mbg.generated Tue Aug 28 16:01:16 CST 2018
     */
    int insert(SysRolePower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_power
     *
     * @mbg.generated Tue Aug 28 16:01:16 CST 2018
     */
    int insertSelective(SysRolePower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_power
     *
     * @mbg.generated Tue Aug 28 16:01:16 CST 2018
     */
    List<SysRolePower> selectByExample(SysRolePowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_power
     *
     * @mbg.generated Tue Aug 28 16:01:16 CST 2018
     */
    SysRolePower selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_power
     *
     * @mbg.generated Tue Aug 28 16:01:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysRolePower record, @Param("example") SysRolePowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_power
     *
     * @mbg.generated Tue Aug 28 16:01:16 CST 2018
     */
    int updateByExample(@Param("record") SysRolePower record, @Param("example") SysRolePowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_power
     *
     * @mbg.generated Tue Aug 28 16:01:16 CST 2018
     */
    int updateByPrimaryKeySelective(SysRolePower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_power
     *
     * @mbg.generated Tue Aug 28 16:01:16 CST 2018
     */
    int updateByPrimaryKey(SysRolePower record);
}